// <auto-generated />
using System;
using DATN_TMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATN_TMS.Migrations
{
    [DbContext(typeof(QuanLyDoAnTotNghiepContext))]
    [Migration("20260301214616_RemoveIsUnicodeFalse_ForUnicodeColumns")]
    partial class RemoveIsUnicodeFalse_ForUnicodeColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DATN_TMS.Models.BaoCaoNop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileBaocao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_baocao");

                    b.Property<int?>("IdDeTai")
                        .HasColumnType("int")
                        .HasColumnName("id_de_tai");

                    b.Property<int?>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<int?>("IdSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("id_sinh_vien");

                    b.Property<DateTime?>("NgayNop")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_nop");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhan_xet");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("stt");

                    b.Property<string>("TenBaoCao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_bao_cao");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__BaoCaoNo__3213E83F9D634EFF");

                    b.HasIndex("IdDeTai");

                    b.HasIndex("IdDot");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("BaoCaoNop", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.BaoCaoThongKe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTietTuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("chi_tiet_tuan");

                    b.Property<int>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<DateTime>("NgayTinh")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tinh");

                    b.Property<int>("SoLuongDeTai")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_de_tai");

                    b.Property<int>("SoLuongSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_sinh_vien");

                    b.Property<int?>("SoLuongTaskTuan")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_task_tuan");

                    b.Property<double?>("TiLeHoanThanh")
                        .HasColumnType("float")
                        .HasColumnName("ti_le_hoan_thanh");

                    b.HasKey("Id")
                        .HasName("PK__BaoCaoTh__3213E83FBEC73E3E");

                    b.HasIndex("IdDot");

                    b.ToTable("BaoCaoThongKe", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.BoMon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdNguoiSua")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_sua");

                    b.Property<int?>("IdNguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_tao");

                    b.Property<DateOnly?>("NgaySua")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sua");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tao");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("stt");

                    b.Property<string>("TenBoMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_bo_mon");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ten_viet_tat");

                    b.HasKey("Id")
                        .HasName("PK__BoMon__3213E83F3BEBEC59");

                    b.HasIndex("IdNguoiSua");

                    b.HasIndex("IdNguoiTao");

                    b.ToTable("BoMon", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.CauHinhPhieuChamDot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<int?>("IdLoaiPhieu")
                        .HasColumnType("int")
                        .HasColumnName("id_loai_phieu");

                    b.Property<string>("VaiTroCham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vai_tro_cham");

                    b.HasKey("Id")
                        .HasName("PK__CauHinhP__3213E83FF7593742");

                    b.HasIndex("IdDot");

                    b.HasIndex("IdLoaiPhieu");

                    b.ToTable("CauHinhPhieuCham_Dot", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.CauHinhThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DoiTuongNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("doi_tuong_nhan");

                    b.Property<int?>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<int?>("IdMau")
                        .HasColumnType("int")
                        .HasColumnName("id_mau");

                    b.Property<string>("LoaiSuKien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_su_kien");

                    b.Property<string>("MocThoiGian")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("moc_thoi_gian");

                    b.Property<string>("NoiDungMau")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung_mau");

                    b.Property<int?>("SoNgayChenhLech")
                        .HasColumnType("int")
                        .HasColumnName("so_ngay_chenh_lech");

                    b.Property<string>("TieuDeMau")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de_mau");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__CauHinhT__3213E83FAE9266C5");

                    b.HasIndex("IdDot");

                    b.HasIndex("IdMau");

                    b.ToTable("CauHinhThongBao", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.ChiTietCtdt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DieuKienTienQuyet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dieu_kien_tien_quyet");

                    b.Property<int?>("HocKiToChuc")
                        .HasColumnType("int")
                        .HasColumnName("hoc_ki_to_chuc");

                    b.Property<int?>("IdCtdt")
                        .HasColumnType("int")
                        .HasColumnName("id_ctdt");

                    b.Property<string>("LoaiHocPhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_hoc_phan");

                    b.Property<string>("MaHocPhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_hoc_phan");

                    b.Property<int?>("SoTinChi")
                        .HasColumnType("int")
                        .HasColumnName("so_tin_chi");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("stt");

                    b.Property<string>("TenHocPhan")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ten_hoc_phan");

                    b.HasKey("Id")
                        .HasName("PK__ChiTiet___3213E83F9F0D490A");

                    b.HasIndex("IdCtdt");

                    b.ToTable("ChiTiet_CTDT", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdKhoaHoc")
                        .HasColumnType("int")
                        .HasColumnName("id_khoa_hoc");

                    b.Property<int?>("IdNganh")
                        .HasColumnType("int")
                        .HasColumnName("id_nganh");

                    b.Property<string>("MaCtdt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_ctdt");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SttHienThi")
                        .HasColumnType("int")
                        .HasColumnName("stt_hien_thi");

                    b.Property<string>("TenCtdt")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten_ctdt");

                    b.Property<int?>("TongTinChi")
                        .HasColumnType("int")
                        .HasColumnName("tong_tin_chi");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__ChuongTr__3213E83FA682D260");

                    b.HasIndex("IdKhoaHoc");

                    b.HasIndex("IdNganh");

                    b.HasIndex(new[] { "MaCtdt" }, "UQ__ChuongTr__5AE49DFB4AFD3E38")
                        .IsUnique();

                    b.ToTable("ChuongTrinhDaoTao", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.ChuyenNganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdBoMon")
                        .HasColumnType("int")
                        .HasColumnName("id_bo_mon");

                    b.Property<int?>("IdNganh")
                        .HasColumnType("int")
                        .HasColumnName("id_nganh");

                    b.Property<int?>("IdNguoiSua")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_sua");

                    b.Property<int?>("IdNguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_tao");

                    b.Property<DateOnly?>("NgaySua")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sua");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tao");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("stt");

                    b.Property<string>("TenChuyenNganh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_chuyen_nganh");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ten_viet_tat");

                    b.HasKey("Id")
                        .HasName("PK__ChuyenNg__3213E83F894A4D66");

                    b.HasIndex("IdBoMon");

                    b.HasIndex("IdNganh");

                    b.ToTable("ChuyenNganh", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.DangKyNguyenVong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<int?>("IdSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("id_sinh_vien");

                    b.Property<DateTime?>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_dang_ky")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SoTinChiTichLuyHienTai")
                        .HasColumnType("int")
                        .HasColumnName("so_tin_chi_tich_luy_hien_tai");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__DangKyNg__3213E83F60A886FB");

                    b.HasIndex("IdDot");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("DangKyNguyenVong", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.DeCuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DoiTuongNghienCuu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("doi_tuong_nghien_cuu");

                    b.Property<string>("GiaThuyetNghienCuu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gia_thuyet_nghien_cuu");

                    b.Property<int?>("IdDeTai")
                        .HasColumnType("int")
                        .HasColumnName("id_de_tai");

                    b.Property<string>("LyDoChonDeTai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ly_do_chon_de_tai");

                    b.Property<DateTime?>("NgayNop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_nop")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhamViNghienCuu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pham_vi_nghien_cuu");

                    b.Property<string>("PhuongPhapNghienCuu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phuong_phap_nghien_cuu");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__DeCuong__3213E83F72FF5BD3");

                    b.HasIndex(new[] { "IdDeTai" }, "UQ__DeCuong__ED6A0B2C5DB52DF5")
                        .IsUnique()
                        .HasFilter("[id_de_tai] IS NOT NULL");

                    b.ToTable("DeCuong", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.DeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CongNgheSuDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cong_nghe_su_dung");

                    b.Property<int?>("IdChuyenNganh")
                        .HasColumnType("int")
                        .HasColumnName("id_chuyen_nganh");

                    b.Property<int?>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<int?>("IdGvhd")
                        .HasColumnType("int")
                        .HasColumnName("id_gvhd");

                    b.Property<int?>("IdNguoiDeXuat")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_de_xuat");

                    b.Property<string>("MaDeTai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_de_tai");

                    b.Property<string>("MucTieuChinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("muc_tieu_chinh");

                    b.Property<int?>("NguoiDuyet")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_duyet");

                    b.Property<string>("NhanXetDuyet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhan_xet_duyet");

                    b.Property<string>("PhamViChucNang")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pham_vi_chuc_nang");

                    b.Property<string>("SanPhamKetQuaDuKien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("san_pham_ket_qua_du_kien");

                    b.Property<string>("TenDeTai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_de_tai");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CHO_DUYET")
                        .HasColumnName("trang_thai");

                    b.Property<string>("YeuCauTinhMoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("yeu_cau_tinh_moi");

                    b.HasKey("Id")
                        .HasName("PK__DeTai__3213E83F1E04ED43");

                    b.HasIndex("IdChuyenNganh");

                    b.HasIndex("IdDot");

                    b.HasIndex("IdGvhd");

                    b.HasIndex("IdNguoiDeXuat");

                    b.HasIndex("NguoiDuyet");

                    b.ToTable("DeTai", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.DiemChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DiemSo")
                        .HasColumnType("float")
                        .HasColumnName("diem_so");

                    b.Property<int?>("IdNguoiCham")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_cham");

                    b.Property<int?>("IdPhienBaoVe")
                        .HasColumnType("int")
                        .HasColumnName("id_phien_bao_ve");

                    b.Property<int?>("IdSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("id_sinh_vien");

                    b.Property<int?>("IdTieuChi")
                        .HasColumnType("int")
                        .HasColumnName("id_tieu_chi");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhan_xet");

                    b.HasKey("Id")
                        .HasName("PK__DiemChiT__3213E83FCE2026C4");

                    b.HasIndex("IdNguoiCham");

                    b.HasIndex("IdPhienBaoVe");

                    b.HasIndex("IdSinhVien");

                    b.HasIndex("IdTieuChi");

                    b.ToTable("DiemChiTiet", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.DonPhucKhao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<int?>("IdSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("id_sinh_vien");

                    b.Property<string>("MinhChungLink")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("minh_chung_link");

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_gui")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_xu_ly");

                    b.Property<string>("NoiDungKhieuNai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung_khieu_nai");

                    b.Property<string>("PhanHoiCuaGv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phan_hoi_cua_gv");

                    b.Property<string>("TieuDeKhieuNai")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de_khieu_nai");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("CHO_XU_LY")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__DonPhucK__3213E83FF2190074");

                    b.HasIndex("IdDot");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("DonPhucKhao", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.DotDoAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdHocKi")
                        .HasColumnType("int")
                        .HasColumnName("id_hoc_ki");

                    b.Property<int?>("IdKhoaHoc")
                        .HasColumnType("int")
                        .HasColumnName("id_khoa_hoc");

                    b.Property<DateOnly?>("NgayBatDauBaoCaoCuoiKi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau_bao_cao_cuoi_ki");

                    b.Property<DateOnly?>("NgayBatDauBaoCaoGiuaKi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau_bao_cao_giua_ki");

                    b.Property<DateOnly?>("NgayBatDauDeXuatDeTai")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau_de_xuat_de_tai");

                    b.Property<DateOnly?>("NgayBatDauDkDuyetNguyenVong")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau_dk_duyet_nguyen_vong");

                    b.Property<DateOnly?>("NgayBatDauDkNguyenVong")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau_dk_nguyen_vong");

                    b.Property<DateOnly?>("NgayBatDauDot")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau_dot");

                    b.Property<DateOnly?>("NgayBatDauDuyetDeXuatDeTai")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau_duyet_de_xuat_de_tai");

                    b.Property<DateOnly?>("NgayBatDauNopDeCuong")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau_nop_de_cuong");

                    b.Property<int?>("NgayCongBoKqBcck")
                        .HasColumnType("int")
                        .HasColumnName("ngay_cong_bo_kq_BCCK");

                    b.Property<int?>("NgayDuyetDxdt")
                        .HasColumnType("int")
                        .HasColumnName("ngay_duyet_DXDT");

                    b.Property<DateOnly?>("NgayKetThucBaoCaoCuoiKi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc_bao_cao_cuoi_ki");

                    b.Property<DateOnly?>("NgayKetThucBaoCaoGiuaKi")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc_bao_cao_giua_ki");

                    b.Property<DateOnly?>("NgayKetThucDeXuatDeTai")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc_de_xuat_de_tai");

                    b.Property<DateOnly?>("NgayKetThucDkDuyetNguyenVong")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc_dk_duyet_nguyen_vong");

                    b.Property<DateOnly?>("NgayKetThucDkNguyenVong")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc_dk_nguyen_vong");

                    b.Property<DateOnly?>("NgayKetThucDot")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc_dot");

                    b.Property<DateOnly?>("NgayKetThucDuyetDeXuatDeTai")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc_duyet_de_xuat_de_tai");

                    b.Property<DateOnly?>("NgayKetThucNopDeCuong")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc_nop_de_cuong");

                    b.Property<int?>("NgayLapHdBcck")
                        .HasColumnType("int")
                        .HasColumnName("ngay_lap_HD_BCCK");

                    b.Property<int?>("NgayLapHdBcgk")
                        .HasColumnType("int")
                        .HasColumnName("ngay_lap_HD_BCGK");

                    b.Property<int?>("NgayLapHoiDongDuyetDxdt")
                        .HasColumnType("int")
                        .HasColumnName("ngay_lap_hoi_dong_duyet_DXDT");

                    b.Property<int?>("NgayNopTaiLieuBcck")
                        .HasColumnType("int")
                        .HasColumnName("ngay_nop_tai_lieu_BCCK");

                    b.Property<int?>("NgayNopTaiLieuBcgk")
                        .HasColumnType("int")
                        .HasColumnName("ngay_nop_tai_lieu_BCGK");

                    b.Property<string>("TenDot")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten_dot");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__DotDoAn__3213E83F78F1A64D");

                    b.HasIndex("IdHocKi");

                    b.HasIndex("IdKhoaHoc");

                    b.ToTable("DotDoAn", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.GiangVien", b =>
                {
                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("HocVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hoc_vi");

                    b.Property<int?>("IdBoMon")
                        .HasColumnType("int")
                        .HasColumnName("id_bo_mon");

                    b.Property<string>("MaGv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_gv");

                    b.HasKey("IdNguoiDung")
                        .HasName("PK__GiangVie__75D6A11E69E021A6");

                    b.HasIndex("IdBoMon");

                    b.HasIndex(new[] { "MaGv" }, "UQ__GiangVie__0FE116127A5115CB")
                        .IsUnique()
                        .HasFilter("[ma_gv] IS NOT NULL");

                    b.ToTable("GiangVien", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.HocKi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaHocKi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_hoc_ki");

                    b.Property<int?>("NamBatDau")
                        .HasColumnType("int")
                        .HasColumnName("nam_bat_dau");

                    b.Property<int?>("NamKetThuc")
                        .HasColumnType("int")
                        .HasColumnName("nam_ket_thuc");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trang_thai");

                    b.Property<int?>("TuanBatDau")
                        .HasColumnType("int")
                        .HasColumnName("tuan_bat_dau");

                    b.HasKey("Id")
                        .HasName("PK__HocKi__3213E83FE7F52CAF");

                    b.ToTable("HocKi", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.HoiDongBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("dia_diem");

                    b.Property<int?>("IdBoMon")
                        .HasColumnType("int")
                        .HasColumnName("id_bo_mon");

                    b.Property<int?>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<int?>("IdNguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_tao");

                    b.Property<string>("LoaiHoiDong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("loai_hoi_dong");

                    b.Property<string>("MaHoiDong")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_hoi_dong");

                    b.Property<DateOnly?>("NgayBaoCao")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bao_cao");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<string>("TenHoiDong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_hoi_dong");

                    b.Property<TimeOnly?>("ThoiGianDuKien")
                        .HasColumnType("time")
                        .HasColumnName("thoi_gian_du_kien");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__HoiDongB__3213E83F5AD4E357");

                    b.HasIndex("IdBoMon");

                    b.HasIndex("IdDot");

                    b.HasIndex("IdNguoiTao");

                    b.ToTable("HoiDongBaoCao", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.KeHoachCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("GioBatDau")
                        .HasColumnType("time")
                        .HasColumnName("gio_bat_dau");

                    b.Property<TimeOnly?>("GioBatDauThucTe")
                        .HasColumnType("time")
                        .HasColumnName("gio_bat_dau_thuc_te");

                    b.Property<TimeOnly?>("GioKetThuc")
                        .HasColumnType("time")
                        .HasColumnName("gio_ket_thuc");

                    b.Property<TimeOnly?>("GioKetThucThucTe")
                        .HasColumnType("time")
                        .HasColumnName("gio_ket_thuc_thuc_te");

                    b.Property<int?>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<int?>("IdFileMinhChung")
                        .HasColumnType("int")
                        .HasColumnName("id_file_minh_chung");

                    b.Property<int?>("IdSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("id_sinh_vien");

                    b.Property<string>("MoTaCongViec")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta_cong_viec");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("stt");

                    b.Property<string>("TenCongViec")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten_cong_viec");

                    b.Property<byte?>("ThuTrongTuan")
                        .HasColumnType("tinyint")
                        .HasColumnName("thu_trong_tuan");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.Property<int?>("Tuan")
                        .HasColumnType("int")
                        .HasColumnName("tuan");

                    b.HasKey("Id")
                        .HasName("PK__KeHoachC__3213E83F15422157");

                    b.HasIndex("IdDot");

                    b.HasIndex("IdFileMinhChung");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("KeHoachCongViec", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.KetQuaBaoVeSinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiemChu")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("diem_chu");

                    b.Property<double?>("DiemTongKet")
                        .HasColumnType("float")
                        .HasColumnName("diem_tong_ket");

                    b.Property<int?>("IdPhienBaoVe")
                        .HasColumnType("int")
                        .HasColumnName("id_phien_bao_ve");

                    b.Property<int?>("IdSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("id_sinh_vien");

                    b.Property<string>("KetQua")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ket_qua");

                    b.HasKey("Id")
                        .HasName("PK__KetQuaBa__3213E83FC3C8EAFE");

                    b.HasIndex("IdPhienBaoVe");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("KetQuaBaoVe_SinhVien", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.KetQuaHocTap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiemChu")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("diem_chu");

                    b.Property<double?>("DiemSo")
                        .HasColumnType("float")
                        .HasColumnName("diem_so");

                    b.Property<double?>("Gpa")
                        .HasColumnType("float")
                        .HasColumnName("GPA");

                    b.Property<int?>("IdSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("id_sinh_vien");

                    b.Property<bool?>("KetQua")
                        .HasColumnType("bit")
                        .HasColumnName("ket_qua");

                    b.Property<string>("MaHocPhan")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ma_hoc_phan");

                    b.Property<double?>("SoTc")
                        .HasColumnType("float")
                        .HasColumnName("so_tc");

                    b.Property<int?>("Stt")
                        .HasColumnType("int")
                        .HasColumnName("stt");

                    b.Property<string>("TenHocPhan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_hoc_phan");

                    b.Property<double?>("TongSoTinChi")
                        .HasColumnType("float")
                        .HasColumnName("tong_so_tin_chi");

                    b.HasKey("Id")
                        .HasName("PK__KetQuaHo__3213E83FA089A7BC");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("KetQuaHocTap", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ma_khoa");

                    b.Property<int?>("NamNhapHoc")
                        .HasColumnType("int")
                        .HasColumnName("nam_nhap_hoc");

                    b.Property<int?>("NamTotNghiep")
                        .HasColumnType("int")
                        .HasColumnName("nam_tot_nghiep");

                    b.Property<string>("TenKhoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_khoa");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__KhoaHoc__3213E83F20FB196F");

                    b.ToTable("KhoaHoc", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.LichSuGuiEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdCauHinh")
                        .HasColumnType("int")
                        .HasColumnName("id_cau_hinh");

                    b.Property<string>("NguoiNhan")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nguoi_nhan");

                    b.Property<DateTime?>("ThoiGianGui")
                        .HasColumnType("datetime")
                        .HasColumnName("thoi_gian_gui");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__LichSuGu__3213E83F1E32A7EE");

                    b.HasIndex("IdCauHinh");

                    b.ToTable("LichSuGuiEmail", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.LoaiPhieuCham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("TenLoaiPhieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_loai_phieu");

                    b.HasKey("Id")
                        .HasName("PK__LoaiPhie__3213E83F0DB7E487");

                    b.HasIndex("NguoiTao");

                    b.ToTable("LoaiPhieuCham", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.MauThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaMau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ma_mau");

                    b.Property<string>("NoiDungThongBao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung_thong_bao");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.HasKey("Id")
                        .HasName("PK__MauThong__3213E83F74BE189B");

                    b.HasIndex(new[] { "MaMau" }, "UQ__MauThong__0BC941DA9A2615E3")
                        .IsUnique()
                        .HasFilter("[ma_mau] IS NOT NULL");

                    b.ToTable("MauThongBao", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.Nganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdBoMon")
                        .HasColumnType("int")
                        .HasColumnName("id_bo_mon");

                    b.Property<int?>("IdNguoiSua")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_sua");

                    b.Property<int?>("IdNguoiTao")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_tao");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ma_nganh");

                    b.Property<DateOnly?>("NgaySua")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sua");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenNganh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_nganh");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ten_viet_tat");

                    b.HasKey("Id")
                        .HasName("PK__Nganh__3213E83F4F091BFD");

                    b.HasIndex("IdBoMon");

                    b.HasIndex("IdNguoiSua");

                    b.HasIndex("IdNguoiTao");

                    b.ToTable("Nganh", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("MicrosoftId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("microsoft_id");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sdt");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__NguoiDun__3213E83F87694B61");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__AB6E61640A0D31B8")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.NhanXetHoiDongDeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDeTai")
                        .HasColumnType("int")
                        .HasColumnName("id_de_tai");

                    b.Property<int>("IdGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("id_giang_vien");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhan_xet");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("IdDeTai");

                    b.HasIndex("IdGiangVien");

                    b.ToTable("NhanXetHoiDongDeTai", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.NhatKyHuongDan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionList")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_list");

                    b.Property<string>("DiaDiemHop")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dia_diem_hop");

                    b.Property<string>("HinhThucHop")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hinh_thuc_hop");

                    b.Property<int?>("IdDot")
                        .HasColumnType("int")
                        .HasColumnName("id_dot");

                    b.Property<string>("MucTieuBuoiHop")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("muc_tieu_buoi_hop");

                    b.Property<DateOnly?>("NgayHop")
                        .HasColumnType("date")
                        .HasColumnName("ngay_hop");

                    b.Property<string>("NoiDungHop")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung_hop");

                    b.Property<string>("TenGvhd")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten_gvhd");

                    b.Property<string>("ThanhVienThamDu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thanh_vien_tham_du");

                    b.Property<TimeOnly?>("ThoiGianHop")
                        .HasColumnType("time")
                        .HasColumnName("thoi_gian_hop");

                    b.HasKey("Id")
                        .HasName("PK__NhatKyHu__3213E83F66EF0287");

                    b.HasIndex("IdDot");

                    b.ToTable("NhatKyHuongDan", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.PhienBaoVe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdHdBaocao")
                        .HasColumnType("int")
                        .HasColumnName("id_hd_baocao");

                    b.Property<int?>("IdSinhVienDeTai")
                        .HasColumnType("int")
                        .HasColumnName("id_sinh_vien_de_tai");

                    b.Property<string>("LinkTaiLieu")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("link_tai_lieu");

                    b.Property<int?>("SttBaoCao")
                        .HasColumnType("int")
                        .HasColumnName("stt_bao_cao");

                    b.HasKey("Id")
                        .HasName("PK__PhienBao__3213E83FC20F68A8");

                    b.HasIndex("IdHdBaocao");

                    b.HasIndex("IdSinhVienDeTai");

                    b.ToTable("PhienBaoVe", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.SinhVien", b =>
                {
                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<int?>("IdChuyenNganh")
                        .HasColumnType("int")
                        .HasColumnName("id_chuyen_nganh");

                    b.Property<int?>("IdKhoaHoc")
                        .HasColumnType("int")
                        .HasColumnName("id_khoa_hoc");

                    b.Property<string>("Mssv")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mssv");

                    b.Property<double?>("TinChiTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("tin_chi_tich_luy");

                    b.HasKey("IdNguoiDung")
                        .HasName("PK__SinhVien__75D6A11ECEB6A0A2");

                    b.HasIndex("IdChuyenNganh");

                    b.HasIndex("IdKhoaHoc");

                    b.HasIndex(new[] { "Mssv" }, "UQ__SinhVien__763F1CDC1BE01D7E")
                        .IsUnique()
                        .HasFilter("[mssv] IS NOT NULL");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.SinhVienDeTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdDeTai")
                        .HasColumnType("int")
                        .HasColumnName("id_de_tai");

                    b.Property<int?>("IdSinhVien")
                        .HasColumnType("int")
                        .HasColumnName("id_sinh_vien");

                    b.Property<DateTime?>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_dang_ky")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhan_xet");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__SinhVien__3213E83FCD622524");

                    b.HasIndex("IdDeTai");

                    b.HasIndex("IdSinhVien");

                    b.ToTable("SinhVien_DeTai", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.ThanhVienHdBaoCao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdGiangVien")
                        .HasColumnType("int")
                        .HasColumnName("id_giang_vien");

                    b.Property<int?>("IdHdBaocao")
                        .HasColumnType("int")
                        .HasColumnName("id_hd_baocao");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vai_tro");

                    b.HasKey("Id")
                        .HasName("PK__ThanhVie__3213E83F87A0B37A");

                    b.HasIndex("IdGiangVien");

                    b.HasIndex("IdHdBaocao");

                    b.ToTable("ThanhVien_HD_BaoCao", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdNguoiNhan")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_nhan");

                    b.Property<string>("LinkLienKet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("link_lien_ket");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.Property<bool?>("TrangThaiXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("trang_thai_xem");

                    b.HasKey("Id")
                        .HasName("PK__ThongBao__3213E83FEB73E563");

                    b.HasIndex("IdNguoiNhan");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.TieuChiChamDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DiemToiDa")
                        .HasColumnType("float")
                        .HasColumnName("diem_toi_da");

                    b.Property<int?>("IdLoaiPhieu")
                        .HasColumnType("int")
                        .HasColumnName("id_loai_phieu");

                    b.Property<string>("MoTaHuongDan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta_huong_dan");

                    b.Property<int?>("SttHienThi")
                        .HasColumnType("int")
                        .HasColumnName("stt_hien_thi");

                    b.Property<string>("TenTieuChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten_tieu_chi");

                    b.Property<double?>("TrongSo")
                        .HasColumnType("float")
                        .HasColumnName("trong_so");

                    b.HasKey("Id")
                        .HasName("PK__TieuChiC__3213E83F976B366C");

                    b.HasIndex("IdLoaiPhieu");

                    b.ToTable("TieuChiChamDiem", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaVaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("TenVaiTro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("Id")
                        .HasName("PK__VaiTro__3213E83FB62466F1");

                    b.HasIndex(new[] { "MaVaiTro" }, "UQ__VaiTro__4AE1754C997E6ABF")
                        .IsUnique()
                        .HasFilter("[ma_vai_tro] IS NOT NULL");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("NguoiDungVaiTro", b =>
                {
                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<int>("IdVaiTro")
                        .HasColumnType("int")
                        .HasColumnName("id_vai_tro");

                    b.HasKey("IdNguoiDung", "IdVaiTro")
                        .HasName("PK__NguoiDun__EEF2E664D32C4259");

                    b.HasIndex("IdVaiTro");

                    b.ToTable("NguoiDung_VaiTro", (string)null);
                });

            modelBuilder.Entity("DATN_TMS.Models.BaoCaoNop", b =>
                {
                    b.HasOne("DATN_TMS.Models.DeTai", "IdDeTaiNavigation")
                        .WithMany("BaoCaoNops")
                        .HasForeignKey("IdDeTai")
                        .HasConstraintName("FK_BCN_DeTai");

                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("BaoCaoNops")
                        .HasForeignKey("IdDot")
                        .HasConstraintName("FK_BCN_Dot");

                    b.HasOne("DATN_TMS.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("BaoCaoNops")
                        .HasForeignKey("IdSinhVien")
                        .HasConstraintName("FK_BCN_SinhVien");

                    b.Navigation("IdDeTaiNavigation");

                    b.Navigation("IdDotNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.BaoCaoThongKe", b =>
                {
                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("BaoCaoThongKes")
                        .HasForeignKey("IdDot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BCTK_Dot");

                    b.Navigation("IdDotNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.BoMon", b =>
                {
                    b.HasOne("DATN_TMS.Models.NguoiDung", "IdNguoiSuaNavigation")
                        .WithMany()
                        .HasForeignKey("IdNguoiSua");

                    b.HasOne("DATN_TMS.Models.NguoiDung", "IdNguoiTaoNavigation")
                        .WithMany()
                        .HasForeignKey("IdNguoiTao");

                    b.Navigation("IdNguoiSuaNavigation");

                    b.Navigation("IdNguoiTaoNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.CauHinhPhieuChamDot", b =>
                {
                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("CauHinhPhieuChamDots")
                        .HasForeignKey("IdDot")
                        .HasConstraintName("FK_CHPC_Dot");

                    b.HasOne("DATN_TMS.Models.LoaiPhieuCham", "IdLoaiPhieuNavigation")
                        .WithMany("CauHinhPhieuChamDots")
                        .HasForeignKey("IdLoaiPhieu")
                        .HasConstraintName("FK_CHPC_LoaiPhieu");

                    b.Navigation("IdDotNavigation");

                    b.Navigation("IdLoaiPhieuNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.CauHinhThongBao", b =>
                {
                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("CauHinhThongBaos")
                        .HasForeignKey("IdDot")
                        .HasConstraintName("FK_CHTB_Dot");

                    b.HasOne("DATN_TMS.Models.MauThongBao", "IdMauNavigation")
                        .WithMany("CauHinhThongBaos")
                        .HasForeignKey("IdMau")
                        .HasConstraintName("FK_CHTB_Mau");

                    b.Navigation("IdDotNavigation");

                    b.Navigation("IdMauNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.ChiTietCtdt", b =>
                {
                    b.HasOne("DATN_TMS.Models.ChuongTrinhDaoTao", "IdCtdtNavigation")
                        .WithMany("ChiTietCtdts")
                        .HasForeignKey("IdCtdt")
                        .HasConstraintName("FK_CTDT_ChiTiet");

                    b.Navigation("IdCtdtNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.ChuongTrinhDaoTao", b =>
                {
                    b.HasOne("DATN_TMS.Models.KhoaHoc", "IdKhoaHocNavigation")
                        .WithMany("ChuongTrinhDaoTaos")
                        .HasForeignKey("IdKhoaHoc")
                        .HasConstraintName("FK_CTDT_KhoaHoc");

                    b.HasOne("DATN_TMS.Models.Nganh", "IdNganhNavigation")
                        .WithMany("ChuongTrinhDaoTaos")
                        .HasForeignKey("IdNganh")
                        .HasConstraintName("FK_CTDT_Nganh");

                    b.Navigation("IdKhoaHocNavigation");

                    b.Navigation("IdNganhNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.ChuyenNganh", b =>
                {
                    b.HasOne("DATN_TMS.Models.BoMon", "IdBoMonNavigation")
                        .WithMany("ChuyenNganhs")
                        .HasForeignKey("IdBoMon")
                        .HasConstraintName("FK_CN_BoMon");

                    b.HasOne("DATN_TMS.Models.Nganh", "IdNganhNavigation")
                        .WithMany("ChuyenNganhs")
                        .HasForeignKey("IdNganh")
                        .HasConstraintName("FK_CN_Nganh");

                    b.Navigation("IdBoMonNavigation");

                    b.Navigation("IdNganhNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.DangKyNguyenVong", b =>
                {
                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("DangKyNguyenVongs")
                        .HasForeignKey("IdDot")
                        .HasConstraintName("FK_DKNV_Dot");

                    b.HasOne("DATN_TMS.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("DangKyNguyenVongs")
                        .HasForeignKey("IdSinhVien")
                        .HasConstraintName("FK_DKNV_SinhVien");

                    b.Navigation("IdDotNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.DeCuong", b =>
                {
                    b.HasOne("DATN_TMS.Models.DeTai", "IdDeTaiNavigation")
                        .WithOne("DeCuong")
                        .HasForeignKey("DATN_TMS.Models.DeCuong", "IdDeTai")
                        .HasConstraintName("FK_DeCuong_DeTai");

                    b.Navigation("IdDeTaiNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.DeTai", b =>
                {
                    b.HasOne("DATN_TMS.Models.ChuyenNganh", "IdChuyenNganhNavigation")
                        .WithMany("DeTais")
                        .HasForeignKey("IdChuyenNganh")
                        .HasConstraintName("FK_DeTai_ChuyenNganh");

                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("DeTais")
                        .HasForeignKey("IdDot")
                        .HasConstraintName("FK_DeTai_Dot");

                    b.HasOne("DATN_TMS.Models.GiangVien", "IdGvhdNavigation")
                        .WithMany("DeTaiIdGvhdNavigations")
                        .HasForeignKey("IdGvhd")
                        .HasConstraintName("FK_DeTai_GVHD");

                    b.HasOne("DATN_TMS.Models.NguoiDung", "IdNguoiDeXuatNavigation")
                        .WithMany("DeTais")
                        .HasForeignKey("IdNguoiDeXuat")
                        .HasConstraintName("FK_DeTai_NguoiDeXuat");

                    b.HasOne("DATN_TMS.Models.GiangVien", "NguoiDuyetNavigation")
                        .WithMany("DeTaiNguoiDuyetNavigations")
                        .HasForeignKey("NguoiDuyet")
                        .HasConstraintName("FK_DeTai_NguoiDuyet");

                    b.Navigation("IdChuyenNganhNavigation");

                    b.Navigation("IdDotNavigation");

                    b.Navigation("IdGvhdNavigation");

                    b.Navigation("IdNguoiDeXuatNavigation");

                    b.Navigation("NguoiDuyetNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.DiemChiTiet", b =>
                {
                    b.HasOne("DATN_TMS.Models.GiangVien", "IdNguoiChamNavigation")
                        .WithMany("DiemChiTiets")
                        .HasForeignKey("IdNguoiCham")
                        .HasConstraintName("FK_DCT_NguoiCham");

                    b.HasOne("DATN_TMS.Models.PhienBaoVe", "IdPhienBaoVeNavigation")
                        .WithMany("DiemChiTiets")
                        .HasForeignKey("IdPhienBaoVe")
                        .HasConstraintName("FK_DCT_Phien");

                    b.HasOne("DATN_TMS.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("DiemChiTiets")
                        .HasForeignKey("IdSinhVien")
                        .HasConstraintName("FK_DCT_SinhVien");

                    b.HasOne("DATN_TMS.Models.TieuChiChamDiem", "IdTieuChiNavigation")
                        .WithMany("DiemChiTiets")
                        .HasForeignKey("IdTieuChi")
                        .HasConstraintName("FK_DCT_TieuChi");

                    b.Navigation("IdNguoiChamNavigation");

                    b.Navigation("IdPhienBaoVeNavigation");

                    b.Navigation("IdSinhVienNavigation");

                    b.Navigation("IdTieuChiNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.DonPhucKhao", b =>
                {
                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("DonPhucKhaos")
                        .HasForeignKey("IdDot")
                        .HasConstraintName("FK_DPK_Dot");

                    b.HasOne("DATN_TMS.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("DonPhucKhaos")
                        .HasForeignKey("IdSinhVien")
                        .HasConstraintName("FK_DPK_SinhVien");

                    b.Navigation("IdDotNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.DotDoAn", b =>
                {
                    b.HasOne("DATN_TMS.Models.HocKi", "IdHocKiNavigation")
                        .WithMany("DotDoAns")
                        .HasForeignKey("IdHocKi")
                        .HasConstraintName("FK_Dot_HocKi");

                    b.HasOne("DATN_TMS.Models.KhoaHoc", "IdKhoaHocNavigation")
                        .WithMany("DotDoAns")
                        .HasForeignKey("IdKhoaHoc")
                        .HasConstraintName("FK_Dot_KhoaHoc");

                    b.Navigation("IdHocKiNavigation");

                    b.Navigation("IdKhoaHocNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.GiangVien", b =>
                {
                    b.HasOne("DATN_TMS.Models.BoMon", "IdBoMonNavigation")
                        .WithMany("GiangViens")
                        .HasForeignKey("IdBoMon")
                        .HasConstraintName("FK_GV_BoMon");

                    b.HasOne("DATN_TMS.Models.NguoiDung", "IdNguoiDungNavigation")
                        .WithOne("GiangVien")
                        .HasForeignKey("DATN_TMS.Models.GiangVien", "IdNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_GV_NguoiDung");

                    b.Navigation("IdBoMonNavigation");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.HoiDongBaoCao", b =>
                {
                    b.HasOne("DATN_TMS.Models.BoMon", "IdBoMonNavigation")
                        .WithMany("HoiDongBaoCaos")
                        .HasForeignKey("IdBoMon")
                        .HasConstraintName("FK_HDBC_BoMon");

                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("HoiDongBaoCaos")
                        .HasForeignKey("IdDot")
                        .HasConstraintName("FK_HDBC_Dot");

                    b.HasOne("DATN_TMS.Models.NguoiDung", "IdNguoiTaoNavigation")
                        .WithMany()
                        .HasForeignKey("IdNguoiTao");

                    b.Navigation("IdBoMonNavigation");

                    b.Navigation("IdDotNavigation");

                    b.Navigation("IdNguoiTaoNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.KeHoachCongViec", b =>
                {
                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("KeHoachCongViecs")
                        .HasForeignKey("IdDot")
                        .HasConstraintName("FK_KHCV_Dot");

                    b.HasOne("DATN_TMS.Models.BaoCaoNop", "IdFileMinhChungNavigation")
                        .WithMany("KeHoachCongViecs")
                        .HasForeignKey("IdFileMinhChung")
                        .HasConstraintName("FK_KHCV_MinhChung");

                    b.HasOne("DATN_TMS.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("KeHoachCongViecs")
                        .HasForeignKey("IdSinhVien")
                        .HasConstraintName("FK_KHCV_SinhVien");

                    b.Navigation("IdDotNavigation");

                    b.Navigation("IdFileMinhChungNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.KetQuaBaoVeSinhVien", b =>
                {
                    b.HasOne("DATN_TMS.Models.PhienBaoVe", "IdPhienBaoVeNavigation")
                        .WithMany("KetQuaBaoVeSinhViens")
                        .HasForeignKey("IdPhienBaoVe")
                        .HasConstraintName("FK_KQBV_Phien");

                    b.HasOne("DATN_TMS.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("KetQuaBaoVeSinhViens")
                        .HasForeignKey("IdSinhVien")
                        .HasConstraintName("FK_KQBV_SinhVien");

                    b.Navigation("IdPhienBaoVeNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.KetQuaHocTap", b =>
                {
                    b.HasOne("DATN_TMS.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("KetQuaHocTaps")
                        .HasForeignKey("IdSinhVien")
                        .HasConstraintName("FK_KQHT_SinhVien");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.LichSuGuiEmail", b =>
                {
                    b.HasOne("DATN_TMS.Models.CauHinhThongBao", "IdCauHinhNavigation")
                        .WithMany("LichSuGuiEmails")
                        .HasForeignKey("IdCauHinh")
                        .HasConstraintName("FK_LSGE_CauHinh");

                    b.Navigation("IdCauHinhNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.LoaiPhieuCham", b =>
                {
                    b.HasOne("DATN_TMS.Models.NguoiDung", "NguoiTaoNavigation")
                        .WithMany("LoaiPhieuChams")
                        .HasForeignKey("NguoiTao")
                        .HasConstraintName("FK_LPC_NguoiTao");

                    b.Navigation("NguoiTaoNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.Nganh", b =>
                {
                    b.HasOne("DATN_TMS.Models.BoMon", "IdBoMonNavigation")
                        .WithMany("Nganhs")
                        .HasForeignKey("IdBoMon")
                        .HasConstraintName("FK_Nganh_BoMon");

                    b.HasOne("DATN_TMS.Models.NguoiDung", "IdNguoiSuaNavigation")
                        .WithMany()
                        .HasForeignKey("IdNguoiSua");

                    b.HasOne("DATN_TMS.Models.NguoiDung", "IdNguoiTaoNavigation")
                        .WithMany()
                        .HasForeignKey("IdNguoiTao");

                    b.Navigation("IdBoMonNavigation");

                    b.Navigation("IdNguoiSuaNavigation");

                    b.Navigation("IdNguoiTaoNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.NhanXetHoiDongDeTai", b =>
                {
                    b.HasOne("DATN_TMS.Models.DeTai", "DeTai")
                        .WithMany()
                        .HasForeignKey("IdDeTai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NXHD_DeTai");

                    b.HasOne("DATN_TMS.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("IdGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NXHD_GiangVien");

                    b.Navigation("DeTai");

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("DATN_TMS.Models.NhatKyHuongDan", b =>
                {
                    b.HasOne("DATN_TMS.Models.DotDoAn", "IdDotNavigation")
                        .WithMany("NhatKyHuongDans")
                        .HasForeignKey("IdDot")
                        .HasConstraintName("FK_NKHD_Dot");

                    b.Navigation("IdDotNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.PhienBaoVe", b =>
                {
                    b.HasOne("DATN_TMS.Models.HoiDongBaoCao", "IdHdBaocaoNavigation")
                        .WithMany("PhienBaoVes")
                        .HasForeignKey("IdHdBaocao")
                        .HasConstraintName("FK_PBV_HD");

                    b.HasOne("DATN_TMS.Models.SinhVienDeTai", "IdSinhVienDeTaiNavigation")
                        .WithMany("PhienBaoVes")
                        .HasForeignKey("IdSinhVienDeTai")
                        .HasConstraintName("FK_PBV_SVDT");

                    b.Navigation("IdHdBaocaoNavigation");

                    b.Navigation("IdSinhVienDeTaiNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.SinhVien", b =>
                {
                    b.HasOne("DATN_TMS.Models.ChuyenNganh", "IdChuyenNganhNavigation")
                        .WithMany("SinhViens")
                        .HasForeignKey("IdChuyenNganh")
                        .HasConstraintName("FK_SV_ChuyenNganh");

                    b.HasOne("DATN_TMS.Models.KhoaHoc", "IdKhoaHocNavigation")
                        .WithMany("SinhViens")
                        .HasForeignKey("IdKhoaHoc")
                        .HasConstraintName("FK_SV_KhoaHoc");

                    b.HasOne("DATN_TMS.Models.NguoiDung", "IdNguoiDungNavigation")
                        .WithOne("SinhVien")
                        .HasForeignKey("DATN_TMS.Models.SinhVien", "IdNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_SV_NguoiDung");

                    b.Navigation("IdChuyenNganhNavigation");

                    b.Navigation("IdKhoaHocNavigation");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.SinhVienDeTai", b =>
                {
                    b.HasOne("DATN_TMS.Models.DeTai", "IdDeTaiNavigation")
                        .WithMany("SinhVienDeTais")
                        .HasForeignKey("IdDeTai")
                        .HasConstraintName("FK_SVDT_DeTai");

                    b.HasOne("DATN_TMS.Models.SinhVien", "IdSinhVienNavigation")
                        .WithMany("SinhVienDeTais")
                        .HasForeignKey("IdSinhVien")
                        .HasConstraintName("FK_SVDT_SinhVien");

                    b.Navigation("IdDeTaiNavigation");

                    b.Navigation("IdSinhVienNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.ThanhVienHdBaoCao", b =>
                {
                    b.HasOne("DATN_TMS.Models.GiangVien", "IdGiangVienNavigation")
                        .WithMany("ThanhVienHdBaoCaos")
                        .HasForeignKey("IdGiangVien")
                        .HasConstraintName("FK_TVHD_GV");

                    b.HasOne("DATN_TMS.Models.HoiDongBaoCao", "IdHdBaocaoNavigation")
                        .WithMany("ThanhVienHdBaoCaos")
                        .HasForeignKey("IdHdBaocao")
                        .HasConstraintName("FK_TVHD_HD");

                    b.Navigation("IdGiangVienNavigation");

                    b.Navigation("IdHdBaocaoNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.ThongBao", b =>
                {
                    b.HasOne("DATN_TMS.Models.NguoiDung", "IdNguoiNhanNavigation")
                        .WithMany("ThongBaos")
                        .HasForeignKey("IdNguoiNhan")
                        .HasConstraintName("FK_TB_NguoiNhan");

                    b.Navigation("IdNguoiNhanNavigation");
                });

            modelBuilder.Entity("DATN_TMS.Models.TieuChiChamDiem", b =>
                {
                    b.HasOne("DATN_TMS.Models.LoaiPhieuCham", "IdLoaiPhieuNavigation")
                        .WithMany("TieuChiChamDiems")
                        .HasForeignKey("IdLoaiPhieu")
                        .HasConstraintName("FK_TCCD_LoaiPhieu");

                    b.Navigation("IdLoaiPhieuNavigation");
                });

            modelBuilder.Entity("NguoiDungVaiTro", b =>
                {
                    b.HasOne("DATN_TMS.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("IdNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_NDVT_NguoiDung");

                    b.HasOne("DATN_TMS.Models.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("IdVaiTro")
                        .IsRequired()
                        .HasConstraintName("FK_NDVT_VaiTro");
                });

            modelBuilder.Entity("DATN_TMS.Models.BaoCaoNop", b =>
                {
                    b.Navigation("KeHoachCongViecs");
                });

            modelBuilder.Entity("DATN_TMS.Models.BoMon", b =>
                {
                    b.Navigation("ChuyenNganhs");

                    b.Navigation("GiangViens");

                    b.Navigation("HoiDongBaoCaos");

                    b.Navigation("Nganhs");
                });

            modelBuilder.Entity("DATN_TMS.Models.CauHinhThongBao", b =>
                {
                    b.Navigation("LichSuGuiEmails");
                });

            modelBuilder.Entity("DATN_TMS.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Navigation("ChiTietCtdts");
                });

            modelBuilder.Entity("DATN_TMS.Models.ChuyenNganh", b =>
                {
                    b.Navigation("DeTais");

                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("DATN_TMS.Models.DeTai", b =>
                {
                    b.Navigation("BaoCaoNops");

                    b.Navigation("DeCuong");

                    b.Navigation("SinhVienDeTais");
                });

            modelBuilder.Entity("DATN_TMS.Models.DotDoAn", b =>
                {
                    b.Navigation("BaoCaoNops");

                    b.Navigation("BaoCaoThongKes");

                    b.Navigation("CauHinhPhieuChamDots");

                    b.Navigation("CauHinhThongBaos");

                    b.Navigation("DangKyNguyenVongs");

                    b.Navigation("DeTais");

                    b.Navigation("DonPhucKhaos");

                    b.Navigation("HoiDongBaoCaos");

                    b.Navigation("KeHoachCongViecs");

                    b.Navigation("NhatKyHuongDans");
                });

            modelBuilder.Entity("DATN_TMS.Models.GiangVien", b =>
                {
                    b.Navigation("DeTaiIdGvhdNavigations");

                    b.Navigation("DeTaiNguoiDuyetNavigations");

                    b.Navigation("DiemChiTiets");

                    b.Navigation("ThanhVienHdBaoCaos");
                });

            modelBuilder.Entity("DATN_TMS.Models.HocKi", b =>
                {
                    b.Navigation("DotDoAns");
                });

            modelBuilder.Entity("DATN_TMS.Models.HoiDongBaoCao", b =>
                {
                    b.Navigation("PhienBaoVes");

                    b.Navigation("ThanhVienHdBaoCaos");
                });

            modelBuilder.Entity("DATN_TMS.Models.KhoaHoc", b =>
                {
                    b.Navigation("ChuongTrinhDaoTaos");

                    b.Navigation("DotDoAns");

                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("DATN_TMS.Models.LoaiPhieuCham", b =>
                {
                    b.Navigation("CauHinhPhieuChamDots");

                    b.Navigation("TieuChiChamDiems");
                });

            modelBuilder.Entity("DATN_TMS.Models.MauThongBao", b =>
                {
                    b.Navigation("CauHinhThongBaos");
                });

            modelBuilder.Entity("DATN_TMS.Models.Nganh", b =>
                {
                    b.Navigation("ChuongTrinhDaoTaos");

                    b.Navigation("ChuyenNganhs");
                });

            modelBuilder.Entity("DATN_TMS.Models.NguoiDung", b =>
                {
                    b.Navigation("DeTais");

                    b.Navigation("GiangVien");

                    b.Navigation("LoaiPhieuChams");

                    b.Navigation("SinhVien");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("DATN_TMS.Models.PhienBaoVe", b =>
                {
                    b.Navigation("DiemChiTiets");

                    b.Navigation("KetQuaBaoVeSinhViens");
                });

            modelBuilder.Entity("DATN_TMS.Models.SinhVien", b =>
                {
                    b.Navigation("BaoCaoNops");

                    b.Navigation("DangKyNguyenVongs");

                    b.Navigation("DiemChiTiets");

                    b.Navigation("DonPhucKhaos");

                    b.Navigation("KeHoachCongViecs");

                    b.Navigation("KetQuaBaoVeSinhViens");

                    b.Navigation("KetQuaHocTaps");

                    b.Navigation("SinhVienDeTais");
                });

            modelBuilder.Entity("DATN_TMS.Models.SinhVienDeTai", b =>
                {
                    b.Navigation("PhienBaoVes");
                });

            modelBuilder.Entity("DATN_TMS.Models.TieuChiChamDiem", b =>
                {
                    b.Navigation("DiemChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
